# Netlify configuration file
[build]
  command = "npm run build"
  publish = ".next"

# Exclude Supabase Edge Functions from build
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ignore Supabase functions during build
[build.processing.ignore]
  files = ["supabase/functions/**"]

# Environment variable configuration
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.tempolabs.ai https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://images.unsplash.com https://api.dicebear.com; font-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.stripe.com; frame-src 'self' https://zcal.co https://js.stripe.com; object-src 'none'"
